### ISSUE TITLE
Cryptic error message from a simple failure

### ISSUE THREAD

**Issue by hunter-moseley** [MoseleyBioinformaticsLab/pdb_eda#1]
The following command is generating a cryptic error message for users when the issue is simply a problem with downloading or analyzing a PDB entry.
-------------
% python3 -m pdb_eda single 6xyz 6xyz.atom.csv --atom --out-format=csv
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hunter/.local/lib/python3.6/site-packages/pdb_eda/__main__.py", line 51, in <module>
    main(args)
  File "/home/hunter/.local/lib/python3.6/site-packages/pdb_eda/__main__.py", line 44, in main
    singleStructure.main(args)
  File "/home/hunter/.local/lib/python3.6/site-packages/pdb_eda/singleStructure.py", line 28, in main
    analyser.aggregateCloud(radii, slopes, atomL=True, residueL=True, chainL=True)
AttributeError: 'int' object has no attribute 'aggregateCloud'
--------------

The issue is with the implementation of the command line interface that does not test that the creation of an analyzer object is successful.
The needs to be fixed in the singleStructure.py file.
It would be useful if the reason of failure is provided to the user.

**Comment by hunter-moseley** [comment]
Issue is fixed in upcoming version 1.1
